services:
  - type: web
    name: epigrafia-backend
    runtime: python
    buildCommand: pip install --no-cache-dir -r backend/hf_requirements.txt && pip install --no-cache-dir gunicorn
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.6
    plan: free
    autoDeploy: true

